@MelihAkıncı_webTabanliAidatTakipSistemi_HostAddress = http://localhost:5263
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoibWVsaWhhZWVla2luY2kiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBcGFydG1lbnRNYW5hZ2VyIiwiaWQiOiIzIiwiZXhwIjoxNzUyOTE3MTYzLCJpc3MiOiJ3ZWJUYWJhbmxpQWlkYXRUYWtpcFNpc3RlbWkiLCJhdWQiOiJVc2VycyJ9.n9J5Rr1FEVmOciAQn5vpSCZ8YGKPxJowaqQOO0oWzjE


GET {{MelihAkıncı_webTabanliAidatTakipSistemi_HostAddress}}/Home/
Accept: application/json

###

POST {{MelihAkıncı_webTabanliAidatTakipSistemi_HostAddress}}/Home/login
Content-Type: application/json

{
    "username": "melihaeeekinci",
    "password": "1234sad5678"
}
###

POST http://localhost:5263/Home/register
Content-Type: application/json

{
  "name": "Melih",
  "surname": "Akıncı",
  "phoneNumber": "2112112",
  "email": "melihkn",
  "username": "melihaeeekinci",
  "password": "1234sad5678"
}

###

POST {{MelihAkıncı_webTabanliAidatTakipSistemi_HostAddress}}/auth/manager/login 
Content-Type: application/json

{
  "username" : "melihaeeekinci",
  "password" : "1234sad5678"
}
###
PUT {{MelihAkıncı_webTabanliAidatTakipSistemi_HostAddress}}/manager/updateManagerInfos
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "melih",
  "surname": "akıncı",
  "phoneNumber": "1234567890",
  "email": "denememe123qqqggaö"
}

  ###

POST {{MelihAkıncı_webTabanliAidatTakipSistemi_HostAddress}}/manager/addApartment
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "meli22121h12",
  "maxAmountOfResidents": 16,
  "address" : "dsadsadas",
  "floorCount": 4,
  "apartmentUnitCountForEachFloor": 4,
  "isWantedToAutoFillApartmentUnits" : true
}



###
PUT {{MelihAkıncı_webTabanliAidatTakipSistemi_HostAddress}}/manager/updateApartmentInfos
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "kaya apartmanı",
  "apartmentId": 7,
  "maxAmountOfResidents": 12,
  "address" : "düzce kaya mah",
  "floorCount": 8,
  "apartmentUnitCountForEachFloor": 4
}


###

POST {{MelihAkıncı_webTabanliAidatTakipSistemi_HostAddress}}/manager/setApartmentResidentToAnUnit
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "apartmentUnitId": 254,
  "name": "mehmet",
  "surName": "kut",
  "phoneNumber" : "0555454453",
  "email": "mail adresi"
}

###

POST {{MelihAkıncı_webTabanliAidatTakipSistemi_HostAddress}}/manager/setSpecificDebtToApartmentResident
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "mehmet",
  "description": "asansor parası",
  "price" : 2500.99,
  "residentId": 5
}


###