@MelihAkıncı_webTabanliAidatTakipSistemi_HostAddress = http://localhost:5263
@apartmentMananagerToken = 
###

POST {{MelihAkıncı_webTabanliAidatTakipSistemi_HostAddress}}/Home/login
Content-Type: application/json

{
    "username": "melihaeeekinci",
    "password": "1234sad5678"
}
###

POST http://localhost:5263/Home/register
Content-Type: application/json

{
  "name": "Melih",
  "surname": "Akıncı",
  "phoneNumber": "2112112",
  "email": "melihkn",
  "username": "melihaeeekinci",
  "password": "1234sad5678"
}

###

POST {{MelihAkıncı_webTabanliAidatTakipSistemi_HostAddress}}/auth/manager/login 
Content-Type: application/json

{
  "username" : "melihaeeekinci",
  "password" : "1234sad5678"
}
###
PUT {{MelihAkıncı_webTabanliAidatTakipSistemi_HostAddress}}/manager/updateManagerInfos
Content-Type: application/json
Authorization: Bearer {{apartmentMananagerToken}}

{
  "name": "melih",
  "surname": "akıncı",
  "phoneNumber": "1234567890",
  "email": "denememe123qqqggaö"
}

  ###

POST {{MelihAkıncı_webTabanliAidatTakipSistemi_HostAddress}}/manager/addApartment
Content-Type: application/json
Authorization: Bearer {{apartmentMananagerToken}}

{
  "name": "meli22121h12",
  "maxAmountOfResidents": 16,
  "address" : "dsadsadas",
  "floorCount": 4,
  "apartmentUnitCountForEachFloor": 4,
  "isWantedToAutoFillApartmentUnits" : true
}



###
PUT {{MelihAkıncı_webTabanliAidatTakipSistemi_HostAddress}}/manager/updateApartmentInfos
Content-Type: application/json
Authorization: Bearer {{apartmentMananagerToken}}

{
  "name": "kaya apartmanı",
  "apartmentId": 14,
  "maxAmountOfResidents": 12,
  "address" : "düzce kaya mah",
  "floorCount": 8,
  "apartmentUnitCountForEachFloor": 4,
    "maintenanceFeeAmount" : 1500.00

}


###

POST {{MelihAkıncı_webTabanliAidatTakipSistemi_HostAddress}}/manager/setApartmentResidentToAnUnit
Content-Type: application/json
Authorization: Bearer {{apartmentMananagerToken}}

{
  "apartmentUnitId": 258,
  "name": "ahmet",
  "surName": "dartar",
  "phoneNumber" : "223223334443",
  "email": ""
}

###

POST {{MelihAkıncı_webTabanliAidatTakipSistemi_HostAddress}}/manager/setSpecificDebtToApartmentResident
Content-Type: application/json
Authorization: Bearer {{apartmentMananagerToken}}

{
  "name": "mehmet",
  "description": "asansor parası",
  "price" : 2500.99,
  "residentId": 5
}


###


###

GET {{MelihAkıncı_webTabanliAidatTakipSistemi_HostAddress}}/manager/getApartments
Authorization: Bearer {{apartmentMananagerToken}}


###

POST {{MelihAkıncı_webTabanliAidatTakipSistemi_HostAddress}}/manager/getApartmentsUnits
Content-Type: application/json
Authorization: Bearer {{apartmentMananagerToken}}

{
  "apartmentId": 1

}

###

POST {{MelihAkıncı_webTabanliAidatTakipSistemi_HostAddress}}/manager/setMaintenanceFeeToAllResidents
Content-Type: application/json
Authorization: Bearer {{apartmentMananagerToken}}

{
  "apartmentId": 13

}

###

POST {{MelihAkıncı_webTabanliAidatTakipSistemi_HostAddress}}/manager/getAllPaidMaintenanceFees
Content-Type: application/json
Authorization: Bearer {{apartmentMananagerToken}}

{
  "apartmentId": 13

}

###

POST {{MelihAkıncı_webTabanliAidatTakipSistemi_HostAddress}}/manager/getAllPaidSpecialFees
Content-Type: application/json
Authorization: Bearer {{apartmentMananagerToken}}

{
  "apartmentId": 13

}
###
// -------------------------------------------------- Apartment Resident routes ------------------------------------------
@apartmentResidentToken = 

###
POST {{MelihAkıncı_webTabanliAidatTakipSistemi_HostAddress}}/auth/resident/login 
Content-Type: application/json

{
  "username" : "mehmet.kut8752",
  "password" : ""
}
###



PUT {{MelihAkıncı_webTabanliAidatTakipSistemi_HostAddress}}/resident/updateResidentInfos
Content-Type: application/json
Authorization: Bearer {{apartmentResidentToken}}

{
  "name": "mehmet",
  "surname": "kurt",
  "phoneNumber": "1234567890",
  "email": "" 

}
###
GET {{MelihAkıncı_webTabanliAidatTakipSistemi_HostAddress}}/resident/myApartmentUnit
Content-Type: application/json
Authorization: Bearer {{apartmentResidentToken}}

{
 

}
###
GET {{MelihAkıncı_webTabanliAidatTakipSistemi_HostAddress}}/resident/myApartmentUnitMaintenanceFees
Content-Type: application/json
Authorization: Bearer {{apartmentResidentToken}}

{

}



###
GET {{MelihAkıncı_webTabanliAidatTakipSistemi_HostAddress}}/resident/myApartmentUnitSpecialFees
Content-Type: application/json
Authorization: Bearer {{apartmentResidentToken}}

{

}

###
POST {{MelihAkıncı_webTabanliAidatTakipSistemi_HostAddress}}/resident/payMyMaintenanceFee
Content-Type: application/json
Authorization: Bearer {{apartmentResidentToken}}

{
  "maintenanceFeeId" : 4

}

###
POST {{MelihAkıncı_webTabanliAidatTakipSistemi_HostAddress}}/resident/payMySpecialFee
Content-Type: application/json
Authorization: Bearer {{apartmentResidentToken}}

{
  "specialFeeId" : 2

}




















