// <auto-generated />
using System;
using MelihAkıncı_webTabanliAidatTakipSistemi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MelihAkıncı_webTabanliAidatTakipSistemi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250718143501_AddingManagerIdToPaymentNotifications")]
    partial class AddingManagerIdToPaymentNotifications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MelihAkıncı_webTabanliAidatTakipSistemi.Models.Apartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ApartmentUnitCountForEachFloor")
                        .HasColumnType("int");

                    b.Property<int>("FloorCount")
                        .HasColumnType("int");

                    b.Property<decimal>("MaintenanceFeeAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.Property<int>("MaxAmountOfResidents")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.ToTable("Apartments");
                });

            modelBuilder.Entity("MelihAkıncı_webTabanliAidatTakipSistemi.Models.ApartmentManager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("ApartmentManagers");
                });

            modelBuilder.Entity("MelihAkıncı_webTabanliAidatTakipSistemi.Models.ApartmentResident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApartmentUnitId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsFirstLogin")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentUnitId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("ApartmentResidents");
                });

            modelBuilder.Entity("MelihAkıncı_webTabanliAidatTakipSistemi.Models.ApartmentUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApartmentId")
                        .HasColumnType("int");

                    b.Property<int>("ApartmentNumber")
                        .HasColumnType("int");

                    b.Property<string>("ApartmentType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("FloorNumber")
                        .HasColumnType("int");

                    b.Property<bool>("IsOccupied")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("SquareMeters")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.ToTable("ApartmentUnits");
                });

            modelBuilder.Entity("MelihAkıncı_webTabanliAidatTakipSistemi.Models.MaintenanceFee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ApartmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ResidentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResidentId");

                    b.ToTable("MaintenanceFees");
                });

            modelBuilder.Entity("MelihAkıncı_webTabanliAidatTakipSistemi.Models.PaymentNotifications", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ApartmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MaintenanceFeeId")
                        .HasColumnType("int");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NotificationMessage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ReceiptUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ResidentId")
                        .HasColumnType("int");

                    b.Property<int>("SpecialFeeId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("MaintenanceFeeId");

                    b.HasIndex("ResidentId");

                    b.HasIndex("SpecialFeeId");

                    b.ToTable("PaymentNotifications");
                });

            modelBuilder.Entity("MelihAkıncı_webTabanliAidatTakipSistemi.Models.ResidentsSpecificFee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ApartmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ResidentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResidentId");

                    b.ToTable("ResidentsSpecificFees");
                });

            modelBuilder.Entity("MelihAkıncı_webTabanliAidatTakipSistemi.Models.UserRoles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Role = "ApartmentManager"
                        },
                        new
                        {
                            Id = 3,
                            Role = "ApartmentResident"
                        });
                });

            modelBuilder.Entity("MelihAkıncı_webTabanliAidatTakipSistemi.Models.Apartment", b =>
                {
                    b.HasOne("MelihAkıncı_webTabanliAidatTakipSistemi.Models.ApartmentManager", "ApartmentManager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApartmentManager");
                });

            modelBuilder.Entity("MelihAkıncı_webTabanliAidatTakipSistemi.Models.ApartmentManager", b =>
                {
                    b.HasOne("MelihAkıncı_webTabanliAidatTakipSistemi.Models.UserRoles", "UserRoles")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("MelihAkıncı_webTabanliAidatTakipSistemi.Models.ApartmentResident", b =>
                {
                    b.HasOne("MelihAkıncı_webTabanliAidatTakipSistemi.Models.ApartmentUnit", "ApartmentUnit")
                        .WithMany()
                        .HasForeignKey("ApartmentUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MelihAkıncı_webTabanliAidatTakipSistemi.Models.UserRoles", "UserRoles")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApartmentUnit");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("MelihAkıncı_webTabanliAidatTakipSistemi.Models.ApartmentUnit", b =>
                {
                    b.HasOne("MelihAkıncı_webTabanliAidatTakipSistemi.Models.Apartment", "Apartment")
                        .WithMany("ApartmentUnits")
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");
                });

            modelBuilder.Entity("MelihAkıncı_webTabanliAidatTakipSistemi.Models.MaintenanceFee", b =>
                {
                    b.HasOne("MelihAkıncı_webTabanliAidatTakipSistemi.Models.ApartmentResident", "ApartmentResident")
                        .WithMany()
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApartmentResident");
                });

            modelBuilder.Entity("MelihAkıncı_webTabanliAidatTakipSistemi.Models.PaymentNotifications", b =>
                {
                    b.HasOne("MelihAkıncı_webTabanliAidatTakipSistemi.Models.Apartment", "Apartment")
                        .WithMany()
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MelihAkıncı_webTabanliAidatTakipSistemi.Models.MaintenanceFee", "MaintenanceFee")
                        .WithMany()
                        .HasForeignKey("MaintenanceFeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MelihAkıncı_webTabanliAidatTakipSistemi.Models.ApartmentResident", "ApartmentResident")
                        .WithMany()
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MelihAkıncı_webTabanliAidatTakipSistemi.Models.ResidentsSpecificFee", "ResidentsSpecificFee")
                        .WithMany()
                        .HasForeignKey("SpecialFeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");

                    b.Navigation("ApartmentResident");

                    b.Navigation("MaintenanceFee");

                    b.Navigation("ResidentsSpecificFee");
                });

            modelBuilder.Entity("MelihAkıncı_webTabanliAidatTakipSistemi.Models.ResidentsSpecificFee", b =>
                {
                    b.HasOne("MelihAkıncı_webTabanliAidatTakipSistemi.Models.ApartmentResident", "ApartmentResident")
                        .WithMany()
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApartmentResident");
                });

            modelBuilder.Entity("MelihAkıncı_webTabanliAidatTakipSistemi.Models.Apartment", b =>
                {
                    b.Navigation("ApartmentUnits");
                });
#pragma warning restore 612, 618
        }
    }
}
